import { AmnisStakeTool,
    AmnisWithdrawStakeTool,
    AptosAccountAddressTool,
    AptosBalanceTool,
    AptosBurnTokenTool,
    AptosCreateTokenTool,
    AptosGetTokenDetailTool,
    AptosGetTokenPriceTool,
    AptosMintTokenTool,
    AptosTransactionTool,
    AptosTransferTokenTool,
    AriesBorrowTool,
    AriesCreateProfileTool,
    AriesLendTool,
    AriesRepayTool,
    AriesWithdrawTool,
    JouleBorrowTokenTool,
    JouleGetPoolDetails,
    JouleGetUserAllPositions,
    JouleGetUserPosition,
    JouleLendTokenTool,
    JouleRepayTokenTool,
    JouleWithdrawTokenTool,
    LiquidSwapSwapTool,
    LiquidSwapCreatePoolTool,
    LiquidSwapAddLiquidityTool,
    LiquidSwapRemoveLiquidityTool,
    EchelonLendTokenTool,
    EchelonWithdrawTokenTool,
    EchelonRepayTokenTool,
    EchelonBorrowTokenTool,
    EchoStakeTokenTool,
    EchoUnstakeTokenTool,
    OpenAICreateImageTool,
    PanoraSwapTool,
    ThalaStakeTokenTool,
    ThalaUnstakeTokenTool,
    ThalaMintMODTool,
    ThalaRedeemMODTool,
    ThalaAddLiquidityTool,
    ThalaRemoveLiquidityTool 
} from "move-agent-kit";

export type AptosTools = (AptosAccountAddressTool | AmnisStakeTool | AmnisWithdrawStakeTool | AptosBalanceTool | AptosGetTokenDetailTool | AptosTransferTokenTool | AptosBurnTokenTool | AptosMintTokenTool | AptosCreateTokenTool | AptosTransactionTool | AptosGetTokenPriceTool | AriesCreateProfileTool | AriesLendTool | AriesWithdrawTool | AriesBorrowTool | AriesRepayTool | JouleLendTokenTool | JouleBorrowTokenTool | JouleWithdrawTokenTool | JouleRepayTokenTool | JouleGetPoolDetails | JouleGetUserPosition | JouleGetUserAllPositions | LiquidSwapSwapTool | LiquidSwapCreatePoolTool | LiquidSwapAddLiquidityTool | LiquidSwapRemoveLiquidityTool | EchelonLendTokenTool | EchelonWithdrawTokenTool | EchelonRepayTokenTool | EchelonBorrowTokenTool | EchoStakeTokenTool | EchoUnstakeTokenTool | OpenAICreateImageTool | PanoraSwapTool | ThalaStakeTokenTool | ThalaUnstakeTokenTool | ThalaMintMODTool | ThalaRedeemMODTool | ThalaAddLiquidityTool | ThalaRemoveLiquidityTool)[];
